export const UPDATE_DAILY_DATA = 'UPDATE_DAILY_DATA';
export const LOAD_DATA_BY_CITY = 'LOAD_DATA_BY_CITY';
export const UPDATE_CURRENT_DATA = 'UPDATE_CURRENT_DATA';
export const LOAD_DATA_BY_POSITION = 'LOAD_DATA_BY_POSITION';